/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.org.restaurante.models.view;

import com.org.restaurante.models.DTO.Table;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class MesaForm extends javax.swing.JPanel {

    private List<Table> mesas = new ArrayList<>();
    private List<JButton> botones = new ArrayList();
    private JPanel panelGrid;
    
    
    /**
     * Creates new form MesaForm
     */
    public MesaForm() {
        initComponents();
        
        setLayout(new BorderLayout());
        
        panelGrid = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 10)); 
        JScrollPane scroll = new JScrollPane(panelGrid);
        add(scroll, BorderLayout.CENTER);
        
        JButton btnAgregarMesa = new JButton("Agregar Mesa");
        btnAgregarMesa.addActionListener(e -> showFormAdd());
        
        
        JPanel panelBoton = new JPanel();
        panelBoton.add(btnAgregarMesa);
        add(panelBoton, BorderLayout.SOUTH);
        
        mesas.add(new Table(1, 4, true));
        mesas.add(new Table(2, 2, false));
        mesas.add(new Table(3, 6, true));
        mesas.add(new Table(4, 4, true));
        renderTable();
    }
    
    private void showFormAdd(){
        JTextField txtNumero = new JTextField(5);
        JTextField txtAsientos = new JTextField(5);
        
        JPanel panelForm = new JPanel(new GridLayout(1, 1));
        panelForm.add(new JLabel("Numero de mesa: "));
        panelForm.add(txtNumero);
        
        panelForm.add(new JLabel("N° de asientos; "));
        panelForm.add(txtAsientos);
        
        int result = JOptionPane.showConfirmDialog(this, panelForm, "Agregar nuevo Mesa", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION){
            try{
                int numero = Integer.parseInt(txtNumero.getText());
                int asientos = Integer.parseInt(txtAsientos.getText());
                
                // Validar si ya existe ese número de mesa
                numberRepeatOfTable(numero, asientos);
                renderTable();
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Ingresa los valores validos");
            }
        }
        
    }
    
    private void numberRepeatOfTable(Integer numero, Integer asientos){
        boolean yaExiste = mesas.stream().anyMatch(m -> m.getNumero().equals(numero));
        if(yaExiste){
            JOptionPane.showMessageDialog(this, "Ya existe una mesa con ese número.");
            return;
        }else{
            mesas.add(new Table(numero, asientos, true));
        }
    }
    
    private void renderTable(){
        panelGrid.removeAll();
        botones.clear();
        
        for(Table table: mesas){
            JButton btn = new JButton();
            
            btn.setOpaque(true);
            btn.setBorderPainted(false);
            
            btn.setFont(new Font("Arial", Font.PLAIN, 11)); // texto más pequeño
            btn.setPreferredSize(new Dimension(90, 1000));   // ancho x alto deseado
            
            btn.addActionListener(e -> {
               table.setDisponible(!table.getDisponible());
               
            });
            
            botones.add(btn);
           
            panelGrid.add(btn);
        }
        
        
        panelGrid.revalidate();
        panelGrid.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
